language: csharp
solution: Src/ManagedFinanceApi.sln

before_script:
 - chmod +x ./Scripts/build.sh

before_build:
  - nuget restore
 
script:
  - ./Scripts/build.sh

after_failure:
  - ls -LR Src/packages