language: csharp
mono:
  - latest
env: VERSION=0.3.10
solution: Src/ManagedFinanceApi.sln

before_script:
 - chmod +x ./Scripts/build.sh
 
script:
  - ./Scripts/build.sh

after_failure:
  - ls -LR Src/packages